// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mini_3_workspace_access_control.Repo;

#nullable disable

namespace mini_3_workspace_access_control.Repo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_people_email");

                    b.ToTable("people", null, t =>
                        {
                            t.HasCheckConstraint("ck_people_display_name_not_blank", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_people_email_normalized", "email = lower(btrim(email))");

                            t.HasCheckConstraint("ck_people_email_not_blank", "length(btrim(email)) > 0");
                        });
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_code");

                    b.HasIndex("CreatedByPersonId")
                        .HasDatabaseName("ix_workspaces_created_by_person_id");

                    b.ToTable("workspaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_code_format", "code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_workspaces_code_normalized", "code = lower(btrim(code))");

                            t.HasCheckConstraint("ck_workspaces_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.WorkspaceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Viewer")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_invitations");

                    b.HasIndex("CreatedByPersonId")
                        .HasDatabaseName("ix_workspace_invitations_created_by_person_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_workspace_invitations_token_hash");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_workspace_invitations_active_workspace_email")
                        .HasFilter("accepted_at IS NULL AND is_deleted = false");

                    b.ToTable("workspace_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_invitations_accepted_after_create", "accepted_at IS NULL OR accepted_at >= created_at");

                            t.HasCheckConstraint("ck_workspace_invitations_email_normalized", "email = lower(btrim(email))");

                            t.HasCheckConstraint("ck_workspace_invitations_email_not_blank", "length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_workspace_invitations_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_workspace_invitations_role_valid", "role IN ('Owner', 'Manager', 'Editor', 'Viewer')");

                            t.HasCheckConstraint("ck_workspace_invitations_token_hash_hex", "token_hash ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Viewer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_workspace_members_person_id");

                    b.HasIndex("WorkspaceId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_workspace_members_workspace_person_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("WorkspaceId", "Role")
                        .HasDatabaseName("ix_workspace_members_workspace_role_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("workspace_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_members_role_valid", "role IN ('Owner', 'Manager', 'Editor', 'Viewer')");
                        });
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.Workspace", b =>
                {
                    b.HasOne("mini_3_workspace_access_control.Repo.Entity.Person", "CreatedByPerson")
                        .WithMany("CreatedWorkspaces")
                        .HasForeignKey("CreatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_people_created_by_person_id");

                    b.Navigation("CreatedByPerson");
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.WorkspaceInvitation", b =>
                {
                    b.HasOne("mini_3_workspace_access_control.Repo.Entity.Person", "CreatedByPerson")
                        .WithMany("CreatedWorkspaceInvitations")
                        .HasForeignKey("CreatedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invitations_people_created_by_person_id");

                    b.HasOne("mini_3_workspace_access_control.Repo.Entity.Workspace", "Workspace")
                        .WithMany("Invitations")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invitations_workspaces_workspace_id");

                    b.Navigation("CreatedByPerson");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.WorkspaceMember", b =>
                {
                    b.HasOne("mini_3_workspace_access_control.Repo.Entity.Person", "Person")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_people_person_id");

                    b.HasOne("mini_3_workspace_access_control.Repo.Entity.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("Person");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.Person", b =>
                {
                    b.Navigation("CreatedWorkspaceInvitations");

                    b.Navigation("CreatedWorkspaces");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("mini_3_workspace_access_control.Repo.Entity.Workspace", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
